name: Continuous Integration

on:
  push:
    branches: [ trunk ]

jobs:

  tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: '2.0.0'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Nimble
      run: nimble install -y nimble

    - name: Debug build
      run: nimble debug

    - name: Check with Nimalyzer
      run: bin/nimalyzer config/nimalyzer.cfg

    - name: Upload the log
      uses: actions/upload-artifact@v3
      if: failure()
      with:
         name: nimalyzer.log
         path: nimalyzer.log

    - name: Run tests
      run: nimble test

  build_windows:
    needs: tests
    timeout-minutes: 30
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: '2.0.0'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Nimble
      run: nimble install -y nimble

    - name: Release build
      run: |
        nimble install -yd
        nimble release

  build_freebsd:
    needs: tests
    runs-on: macos-12
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Release build
      uses: cross-platform-actions/action@v0.13.0
      with:
        shell: sh
        operating_system: freebsd
        architecture: x86-64
        version: '13.2'
        run: |
          sudo sed -i '' -e 's/quarterly/latest/g' /etc/pkg/FreeBSD.conf
          sudo pkg install -y git nimble
          nimble -y release

  build_linux:
    needs: tests
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: '2.0.0'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Nimble
      run: nimble install -y nimble

    - name: Release build
      run: nimble release
