name: Continuous Integration

on:
  push:
    branches: [ trunk ]

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

#    - name: Cache Nimble
#      id: cache-nimble
#      uses: actions/cache@v3
#      with:
#        path: |
#          ~/.nimble
#        key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
#        restore-keys: |
#          ${{ runner.os }}-nimble-
#      if: runner.os != 'Windows'

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: '1.6.12'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Nimble
      run: nimble install -y nimble

    - name: Debug build
      run: nimble debug

    - name: Check with Nimalyzer
      run: |
        bin/nimalyzer config/nimalyzer.cfg
        bin/nimalyzer config/rules.cfg

    - name: Upload the log
      uses: actions/upload-artifact@v3
      if: failure()
      with:
         name: nimalyzer.log
         path: nimalyzer.log

    - name: Run tests
      run: nimble test
